# Generated by Django 4.2.20 on 2025-04-24 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_discipline', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('second_name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.degree')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('count_people', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LoadType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.discipline')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group')),
                ('load_types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loadtype')),
                ('semesters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
            ],
        ),
        migrations.CreateModel(
            name='WorkloadTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField()),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('subgroups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subgroup')),
                ('workload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workload')),
            ],
        ),
        migrations.CreateModel(
            name='WorkloadDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField()),
                ('subgroups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subgroup')),
                ('workload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workload')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post'),
        ),
        migrations.AddField(
            model_name='employee',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rank'),
        ),
        migrations.AddField(
            model_name='employee',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rate'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='types_of_discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplinetype'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('workload_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workloaddepartment')),
            ],
        ),
    ]
