# Generated by Django 4.2.20 on 2025-04-28 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name_of_discipline',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='disciplinetype',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.degree', verbose_name='Степень'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rank', verbose_name='Ранг'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rate', verbose_name='Ставка'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='second_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
    ]
