# Generated by Django 4.2.20 on 2025-06-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_discipline_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='discipline_types',
        ),
        migrations.AddField(
            model_name='employee',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='employees', to='core.discipline', verbose_name='Дисциплины, которые может вести'),
        ),
    ]
