# Generated by Django 4.2.20 on 2025-06-16 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_employee_discipline_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='main_discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_employees', to='core.discipline', verbose_name='Основная дисциплина'),
        ),
    ]
