# Generated by Django 4.2.20 on 2025-06-16 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_employee_main_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.degree', verbose_name='Степень'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rank', verbose_name='Ранг'),
        ),
    ]
