# Generated by Django 4.2.20 on 2025-06-24 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_workloaddepartment_load_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workloaddepartment',
            name='load_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.loadtype'),
        ),
    ]
