# Generated by Django 4.2.20 on 2025-06-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_workloaddepartment_load_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='main_discipline',
        ),
        migrations.AddField(
            model_name='employee',
            name='main_discipline',
            field=models.ManyToManyField(blank=True, related_name='main_employees', to='core.discipline', verbose_name='Основная дисциплина'),
        ),
    ]
