# Generated by Django 4.2.20 on 2025-06-25 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_employee_main_discipline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workloadteacher',
            name='load_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.loadtype'),
            preserve_default=False,
        ),
    ]
